name: mantani
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  states_rebuilder: ^6.4.0
  navigation_builder: ^0.0.4 
  intl: ^0.19.0
  validators: ^3.0.0
  hive_flutter: ^1.1.0
  firebase_core: ^3.8.0 
  font_awesome_flutter: ^10.8.0
  flutter_svg : ^2.0.15
  provider: ^6.1.2
  get: ^4.6.6
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/